name: update-uv

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  lock:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v3

      - run: |
          echo "\`\`\`" > uv_output.md
          uv lock --upgrade 2>&1 | tee -a uv_output.md
          echo "\`\`\`" >> uv_output.md

      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          committer: hacktobeer <ramsesdebeer@gmail.com>
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update uv lockfile
          title: Update uv lockfile
          body-path: uv_output.md
          branch: update-uv
          base: main
          labels: install
          delete-branch: true
          add-paths: uv.lock